
credentials:
  usernames:
    akhadkhon:
      email: akhadkhon@example.com
      name: Akhadkhon
      password: pbkdf2:sha256:260000$VbTn7Uy8pqOE$e11168f1639f6bc95cfeeb6c223f77664b17d6ec3a2b690d88f5e6f6bc2a9e2d  # password123

cookie:
  name: house_finder_cookie
  key: some_signature_key
  expiry_days: 3

preauthorized:
  emails:
    - akhadkhon@example.com
